filebeat.inputs:
- type: log
  enable: true
  paths:
    - /usr/share/logging/*.log
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]