{
 "title": "metrics-grafana",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success (2xx) per sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (status)(flask_http_request_total{status=~\"2.+\"})) - \n(sum by (status)(flask_http_request_total{status=~\"2.+\"} offset 1m) or (sum by (status)(flask_http_request_total{status=~\"2.+\"})) - (sum by (status)(flask_http_request_total{status=~\"2.+\"}))) or ((sum by (status)(flask_http_request_total{status=~\"2.+\"}))- (sum by (status)(flask_http_request_total{status=~\"2.+\"})))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Client Error (4xx) per sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (status)(flask_http_request_total{status=~\"4.+\"})) - \n(sum by (status)(flask_http_request_total{status=~\"4.+\"} offset 1m) or (sum by (status)(flask_http_request_total{status=~\"4.+\"})) - (sum by (status)(flask_http_request_total{status=~\"4.+\"}))) or ((sum by (status)(flask_http_request_total{status=~\"4.+\"}))- (sum by (status)(flask_http_request_total{status=~\"4.+\"})))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Server Error (5xx) per sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (status)(flask_http_request_total{status=~\"5.+\"})) - \n(sum by (status)(flask_http_request_total{status=~\"5.+\"} offset 1m) or (sum by (status)(flask_http_request_total{status=~\"5.+\"})) - (sum by (status)(flask_http_request_total{status=~\"5.+\"}))) or ((sum by (status)(flask_http_request_total{status=~\"5.+\"}))- (sum by (status)(flask_http_request_total{status=~\"5.+\"})))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request per sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(sum(flask_http_request_total) - sum(flask_http_request_total offset 1m OR on() vector(0))) OR on() vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Invalid Login",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "(sum by (status)(flask_http_request_total{job=\"auth-api\", method=\"POST\",status=\"401\"})) - \n(sum by (status)(flask_http_request_total{job=\"auth-api\", method=\"POST\",status=\"401\"} offset 1m) or (sum by (status)(flask_http_request_total{job=\"auth-api\", method=\"POST\",status=\"401\"})) - (sum by (status)(flask_http_request_total{job=\"auth-api\", method=\"POST\",status=\"401\"}))) or ((sum by (status)(flask_http_request_total{job=\"auth-api\", method=\"POST\",status=\"401\"}))- (sum by (status)(flask_http_request_total{job=\"auth-api\", method=\"POST\",status=\"401\"})))"
    }
   ]
  },
  {
   "title": "Login Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{job=\"auth-api\", method=\"POST\"} - (flask_http_request_total{job=\"auth-api\", method=\"POST\"} offset $__range or (flask_http_request_total{job=\"auth-api\", method=\"POST\"} - flask_http_request_total{job=\"auth-api\", method=\"POST\"}))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Current Up service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  }
 ]
}