{
 "title": "Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current Up Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "HTTP Requests for Each Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total - (flask_http_request_total offset $__range OR (flask_http_request_total - flask_http_request_total))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Down Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(up) - sum(up offset $__range OR on() vector(0)) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Service Error Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"5.+\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Up Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "sum(up) - sum(up offset 1h OR on() vector(0))"
    }
   ]
  }
 ]
}