name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose  -f "docker-compose.yml" up -d --build store-read-db menu-read-db menu-write-db restaurant-db tracking-db order-db rabbitmq redis-db order-api order-load-balancer tracking-api tracking-load-balancer restaurant-api restaurant-load-balancer menu-write-api menu-read-api menu-load-balancer store-read-api store-load-balancer auth-api auth-load-balancer reverse-proxy

      - name: Sleep for 2 minute
        run: sleep 120s
        shell: bash

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Testing with pytest
        run: |
          python3 -m pytest ./test/unit.py
